### ISSUE TITLE
Неправильная обработка при запуске скрипта с ошибкой

### ISSUE THREAD

**Issue by Bibletoon** [Leatherlord/LabsProgramming#1]
Программа должна выдавать ошибку и продолжать работать, но программа падает

**Comment by Leatherlord** [comment]
c7a915eba6425ee225595212d300d82179030068
@Bibletoon

**Comment by Bibletoon** [comment]
Программа точно должна закрываться после обработки ошибки? @Leatherlord

**Comment by Leatherlord** [comment]
Да.
