### ISSUE TITLE
String representatation поля Chapter работает очень странно, при числовом значении этого поля

### ISSUE THREAD

**Issue by Bibletoon** [Leatherlord/LabsProgramming#13]

**Comment by Leatherlord** [comment]
6c929d114e8e85682ea0681b5c0db5a7a9699b20
@Bibletoon

**Comment by Bibletoon** [comment]
Теперь при любом значении поля Chapter выводится слово name, и при сохранении все поля становятся равными name @Leatherlord

**Comment by Bibletoon** [comment]
Шаги для воспроизведения ошибки
1.С помощью команды add создать объект с любыми валидными значениями полей
2.С помощью команды save сохранить результат в файл
3.Открыть файл с данными, в поле Chapter у каждого объекта будет слово name
4.При вводе команды show?, в поле Chapter у каждого объекта будет слово name

**Comment by Leatherlord** [comment]
5369a458bb8508a397bb3e68f7778f82a2b53d4e
@Bibletoon
