### ISSUE TITLE
Заменить (Yeah/Nah) На Y/N

### ISSUE THREAD

**Issue by Bibletoon** [Leatherlord/LabsProgramming#3]
Это по-вурдалакски, будь человеком

**Comment by Leatherlord** [comment]
bed3788a281309e3715da0e9a76dde2d5dc70e4c

**Comment by Leatherlord** [comment]
@Bibletoon

**Comment by Bibletoon** [comment]
@Leatherlord Всё равно не ест Y

**Comment by Leatherlord** [comment]
7a87a64830b5452e725bb4bf8817bc623f7442ba
@Bibletoon
